---

- name: Update Apt Cache
  apt:
    update_cache: yes
   check_mode: no

- name: Create directory for cassandra and keyrings
  file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
  loop:
    - "{{ keyring_path }}"
    - "{{ cassandra_directory }}"

- name: Install Java
  apt:
    name: openjdk-17-jre-headless
    state: present
  check_mode: no
