---
- name: Install required dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - tar

- name: Download Alert Manager binary
  get_url:
    url: "{{ alert_manager_binary_url }}"
    dest: "/tmp/alertmanager-{{ alert_manager_version }}.tar.gz"

- name: Extract Alert Manager binary
  become: true
  unarchive:
    src: "/tmp/alertmanager-{{ alert_manager_version }}.tar.gz"
    dest: /usr/local/bin
    remote_src: yes

- name: Create directory for Alert Manager configuration
  file:
    path: "{{ alert_manager_config_file | dirname }}"
    state: directory

- name: Generate Alert Manager configuration file
  template:
    src: alertmanager.yml.j2
    dest: "{{ alert_manager_config_file }}"
  notify: Restart Alert Manager

- name: Install systemd service
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
  notify: Restart Alert Manager

- name: Start Alert Manager service
  systemd:
    name: alertmanager
    state: started
    enabled: yes


