---
# handlers file for prometheus
#- name: Reload systemd
 # command: systemctl daemon-reload
 # listen: systemd_reload


# Define the handler for reloading systemd
  - name: systemd_reload
    systemd:
      name: "{{ user }}.service"
      state: reloaded
