---
groups:
  - name: salary_api_alerts
    rules:
      - alert: HighCPULoad
        expr: system_cpu_usage > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU Load
          description: 'The CPU load on the server is high.'
      
      - alert: MemoryUsageHigh
        expr: jvm_memory_used_bytes / jvm_memory_max_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High Memory Usage
          description: 'The memory usage on the server is high.'
          
      - alert: DiskSpaceLow
        expr: disk_free_bytes / disk_total_bytes * 100 < 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Low Disk Space
          description: 'The available disk space on the server is critically low.'
          
      - alert: HighRequestLatency
        expr: rate(http_server_requests_seconds_sum{job="salary_api"}[5m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High Request Latency
          description: 'The average request latency is higher than normal.'
      
      # Add more alert rules based on your specific requirements and metrics

