---
# tasks file for fluentd

- name: Install Fluentd
  become: yes
  apt:
    name: "{{ item.name }}"
    state: present
  loop: "{{ fluentd_dependencies }}"

- name: Add Treasure Data repository key
  become: yes
  shell: "{{ fluentd_repository_key_url }} | sh"

- name: Install td-agent
  become: yes
  apt:
    name: "{{ fluentd_package_name }}"
    state: present

- name: Install fluent-plugin-elasticsearch
  become: yes
  gem:
    name: "{{ item.name }}"
  loop: "{{ fluentd_plugins }}"

- name: Copy Fluentd configuration file
  become: yes
  template:
    src: "{{ fluentd_conf_template_src }}"
    dest: "{{ fluentd_conf_dest }}"
    owner: "{{ fluentd_conf_owner }}"
    group: "{{ fluentd_conf_group }}"
    mode: "{{ fluentd_conf_mode }}"
  notify: restart td-agent service

- name: Ensure log directory exists
  become: yes
  file:
    path: "{{ fluentd_log_directory }}"
    state: directory
