---

node_exporter_version: "1.7.0"
node_exporter_architecture: "linux-amd64"
node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.{{ node_exporter_architecture }}.tar.gz"
node_exporter_service_template_src: "node_exporter_service.j2"
node_exporter_service_dest: "/etc/systemd/system/node-exporter.service"
node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"
