---
- name: Create directory for Scylla alerting rules
  ansible.builtin.file:
    path: "{{ scylla_alerting_rules_path | dirname }}"
    state: directory
    mode: '0755'

- name: Copy Scylla alerting rules file
  ansible.builtin.template:
    src: templates/scylla_alerting_rules.yml.j2
    dest: "{{ scylla_alerting_rules_path }}"
    mode: '0644'
  notify: Reload Prometheus

- name: Ensure Prometheus alerts rules are included in Prometheus config
  lineinfile:
    path: "/etc/prometheus/prometheus.yml"
    line: '- scylla_alerting_rules.yml'
    insertafter: 'rule_files'
    state: present
  notify: Reload Prometheus

