---
- name: Create directory for postgres alerting rules
  ansible.builtin.file:
    path: "{{ postgres_alerting_rules_path | dirname }}"
    state: directory
    mode: '0755'

- name: Copy postgres alerting rules file
  ansible.builtin.template:
    src: templates/postgres_alerting_rules.yml.j2
    dest: "{{ postgres_alerting_rules_path }}"
    mode: '0644'
  notify: Reload Prometheus

- name: Ensure Prometheus alerts rules are included in Prometheus config
  lineinfile:
    path: "/etc/prometheus/prometheus.yml"
    line: '- postgres_alerting_rules.yml'
    insertafter: 'rule_files'
    state: present
  notify: Reload Prometheus
