galaxy_info:
  author: Shreya Jaiswal
  description: Fluentd Role for Employee API
  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.1

  platforms:
  - name: Ubuntu
    distribution:
    - jammy
    - focal
  - name: Debian
    distribution:
    - bullseye
    - bookworm

